// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Isbn struct {
	Isbn string `json:"isbn"`
	Olid string `json:"olid"`
}

type Review struct {
	ReviewID   int64           `json:"review_id"`
	Olid       string          `json:"olid"`
	Source     string          `json:"source"`
	ExternalID string          `json:"external_id"`
	Rating     sql.NullFloat64 `json:"rating"`
	Text       sql.NullString  `json:"text"`
}

type Work struct {
	Olid          string         `json:"olid"`
	Title         string         `json:"title"`
	Author        sql.NullString `json:"author"`
	Description   sql.NullString `json:"description"`
	PublishedYear sql.NullInt64  `json:"published_year"`
}
