// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Isbn struct {
	Isbn string
	Olid string
}

type Review struct {
	ReviewID int64
	Olid     string
	Source   string
	Rating   sql.NullFloat64
	Text     sql.NullString
}

type Work struct {
	Olid          string
	Title         string
	Author        sql.NullString
	Description   sql.NullString
	PublishedYear sql.NullInt64
}
