// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

type Isbn struct {
	Isbn string `json:"isbn"`
	Olid string `json:"olid"`
}

type Review struct {
	ReviewID   int64    `json:"review_id"`
	Olid       string   `json:"olid"`
	Source     string   `json:"source"`
	ExternalID string   `json:"external_id"`
	Username   string   `json:"username"`
	Rating     *float64 `json:"rating"`
	Text       *string  `json:"text"`
}

type Work struct {
	Olid          string  `json:"olid"`
	Title         string  `json:"title"`
	Author        *string `json:"author"`
	Description   *string `json:"description"`
	PublishedYear *int64  `json:"published_year"`
}
