// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

type Isbn struct {
	Isbn string `json:"isbn"`
	Olid string `json:"olid"`
}

type Review struct {
	ReviewID   int64    `json:"review_id"`
	Olid       string   `json:"olid"`
	Source     string   `json:"source"`
	ExternalID string   `json:"external_id"`
	Username   string   `json:"username"`
	Rating     *float64 `json:"rating"`
	Text       *string  `json:"text"`
}

type Stat struct {
	Olid        string   `json:"olid"`
	ReviewCount *int64   `json:"review_count"`
	Rating      *float64 `json:"rating"`
}

type Work struct {
	Olid        string  `json:"olid"`
	Title       string  `json:"title"`
	Author      *string `json:"author"`
	Cover       *string `json:"cover"`
	Description *string `json:"description"`
}
